---
packages_to_install:
  - bat
  - ipcalc
  - jq
  - mtr
  - nmap
  - tmux
  - tree

packages_os: "{{ ansible_system | lower }}"
packages_arch: "{{ 'arm64' if ansible_architecture == 'aarch64' else ansible_architecture }}"

packages_base_upgrade: "{{ packages_upgrade | default(false) }}"
packages_lock_timeout: 60

packages_hashicorp_upgrade: "{{ packages_upgrade | default(false) }}"
packages_hashicorp:
  - terraform
  - packer
  - vault

packages_github_upgrade: "{{ packages_upgrade | default(false) }}"
packages_github:
  - name: task
    version_flag: --version
    repo: go-task/task
  - name: argocd
    version_flag: version --client
    repo: argoproj/argo-cd
