---
packages_to_install:
  - ipcalc
  - jq
  - mtr
  - nmap
  - tmux
  - tree

packages_os: "{{ ansible_system | lower }}"
packages_arch: "{{ 'arm64' if ansible_architecture == 'aarch64' else ansible_architecture }}"

packages_base_upgrade: "{{ packages_upgrade | default(false) }}"
packages_lock_timeout: 60

packages_taskfile_binary_path: /usr/bin/task
packages_taskfile_upgrade: "{{ packages_upgrade | default(false) }}"
packages_taskfile_github_latest_release_api: https://api.github.com/repos/go-task/task/releases/latest
packages_taskfile_package_name: "{{ ['task_', packages_os, '_', packages_arch, '.', packages_taskfiles_package_type] | join('') }}"

packages_hashicorp:
  - terraform
  - packer
  - vault
packages_hashicorp_path: /usr/local/bin
packages_hashicorp_upgrade: "{{ packages_upgrade | default(false) }}"
packages_hashicorp_release_api: https://api.releases.hashicorp.com/v1/releases
