---
version: "3"

vars:
  VENV_DIR: .venv

tasks:
  setup:
    desc: Setup a virtual environment and install the dependencies
    cmds:
      - if [ ! -f "{{ .ROOT_DIR }}/{{ .VENV_DIR }}/bin/activate" ]; then python3.11 -m venv {{ .VENV_DIR }}; fi
      - source {{ .VENV_DIR }}/bin/activate && pip install -U pip && pip install --upgrade -r requirements.txt
  lint:
    desc: Perform basic linting of the source code
    cmds:
      - if [ ! -f "{{ .ROOT_DIR }}/{{ .VENV_DIR }}/bin/activate" ]; then task setup; fi
      - source {{ .VENV_DIR }}/bin/activate && pylint library/ || True
      - source {{ .VENV_DIR }}/bin/activate && ANSIBLE_LIBRARY=library ansible-lint
  apply:
    desc: Apply the workstation configuration
    cmds:
      - if [ ! -f "{{ .ROOT_DIR }}/{{ .VENV_DIR }}/bin/activate" ]; then task setup; fi
      - source {{ .VENV_DIR }}/bin/activate && ansible-playbook -i inventory/hosts site.yml
  upgrade:
    desc: Upgrade the workstation configuration
    cmds:
      - if [ ! -f "{{ .ROOT_DIR }}/{{ .VENV_DIR }}/bin/activate" ]; then task setup; fi
      - source {{ .VENV_DIR }}/bin/activate && ansible-playbook -i inventory/hosts site.yml -e packages_upgrade=true
