---
- name: Debian base packages
  when: ansible_os_family == "Debian"
  become: true
  block:
    - name: Upgrade base packages for Debian systems
      ansible.builtin.apt:
        name: "*"
        state: latest   # noqa package-latest
        lock_timeout: "{{ packages_lock_timeout }}"
        update_cache: true
      when: packages_base_upgrade | bool

    - name: Install base packages for Debian systems
      ansible.builtin.apt:
        name: "{{ packages_to_install + _packages_to_install }}"
        state: present
        lock_timeout: "{{ packages_lock_timeout }}"
        update_cache: true

- name: MacOS base packages
  when: ansible_system == "Darwin"
  block:
    - name: Update all the base packages on Mac OS systems
      community.general.homebrew:
        update_homebrew: true
        upgrade_all: true
      when: packages_base_upgrade | bool

    - name: Install base packages on Mac OS systems
      community.general.homebrew:
        name: "{{ packages_to_install + _packages_to_install }}"
        state: present
        update_homebrew: true
