---
- name: Install binary packages from Hashicorp
  hashicorp_package:
    name: "{{ item }}"
    state: present
  become: true
  when: not packages_hashicorp_upgrade | bool
  loop: "{{ packages_hashicorp }}"
  loop_control:
    label: "{{ item }}"

- name: Upgrade binary packages from Hashicorp
  hashicorp_package:
    name: "{{ item }}"
    state: latest
  become: true
  when: packages_hashicorp_upgrade | bool
  loop: "{{ packages_hashicorp }}"
  loop_control:
    label: "{{ item }}"
