---
- name: Include OS-specific variables
  ansible.builtin.include_vars:
    file: "{{ ansible_os_family | lower }}.yml"

- name: Import base package installation tasks
  ansible.builtin.import_tasks:
    file: "base_packages.yml"

- name: Import Linux software installation tasks
  when: ansible_system == "Linux"
  block:
    - name: Import Taskfile installation tasks
      ansible.builtin.import_tasks:
        file: "taskfile.yml"

    - name: Import Hashicorp installation tasks
      ansible.builtin.import_tasks:
        file: "hashicorp.yml"
