---
- name: Get a latest Taskfile release information
  ansible.builtin.uri:
    url: "{{ packages_taskfile_github_latest_release }}"
  register: _taskfile_latest_release

- name: Define a URL of the latest Taskfile package
  ansible.builtin.set_fact:
    _taskfile_latest_url: "{{ _taskfile_latest_release.json | community.general.json_query(_taskfile_latest_release_query) }}"
  vars:
    _taskfile_latest_release_query: "assets[?name==`{{ packages_taskfile_package_name }}`].browser_download_url"

- name: Install the latest Taskfile
  ansible.builtin.apt:
    deb: "{{ _taskfile_latest_url[0] }}"
  become: true
  when: ansible_os_family == "Debian"
