---
- name: Include OS specific vars
  ansible.builtin.include_vars:
    dir: "{{ item }}"
    depth: 1
    extensions: ["yaml", "yml"]
  loop:
    - "{{ ansible_os_family | lower }}"
    - "{{ [ansible_os_family, ansible_distribution] | join('/') | lower }}"
    - "{{ [ansible_os_family, ansible_distribution,
           ansible_distribution_major_version] | join('/') | lower }}"
    - "{{ [ansible_os_family, ansible_distribution,
           ansible_distribution_major_version,
           ansible_distribution_version] | join('/') | lower }}"
  when: lookup('first_found', ['vars', item] | join('/'), errors='ignore')
